version: '3.9'

services:
  app:
    build: .
    container_name: NorthVPNContainer
    command: python -u main.py 
    env_file:
      - .env
    volumes:
      - .:/app       
    ports:
      - "8000:8000"  

